version: "3.9"
services:
  web:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/template:/etc/nginx/template
      - ../src:/var/www/src
    command: /bin/sh -c "DOLLAR=$$ envsubst < /etc/nginx/template/default.conf > /etc/nginx/conf.d/default.conf; nginx -g 'daemon off;' "
    environment:
      TZ: Asia/Tokyo
      SERVER_APP_NAME: app
      SERVER_APP_PORT: ${SERVER_APP_PORT}
      SERVER_WEB_PORT: ${SERVER_WEB_PORT}
    ports:
      - "${SERVER_WEB_PORT}:${SERVER_WEB_PORT}"
    depends_on:
    - app
  app:
    build: ./php
    volumes:
      - ../src:/var/www/src
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./share:/share
    working_dir: /var/www/src
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
  db:
    image: postgres:15.3-alpine
    command: -p ${DATABASE_PORT}
    environment:
      TZ: Tokyo/Asia
      LANG: js_JP.utf8
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: ${DBDATA}
    volumes:
      - pg-symfony6:${DBDATA}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

volumes:
  pg-symfony6:
